[package]
name = "forge"
version = "0.1.2"
edition = "2021"
authors = ["Fred Kyung-jin Rezeau <hello@kyungj.in>"]
description = "Cyberbrawl Forge contract: on chain pricing, timing and settlement of ION."
repository = "https://github.com/litemint/cyberbrawl-contracts"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
ed25519-dalek = "2"
